### ISSUE TITLE
[2pt] Add tranferPolysPrototype and transferAribitsPrototype to muBrambl

### ISSUE THREAD

**Issue by hhs1234567890** [Topl/Brambl-JS#36]

**Comment by hhs1234567890** [comment]
I have completed adding the two functions but the issue is that I am getting the following error 
`No boxes found to fund transaction`
Its really strange because when I copied the body of the request into postman I did not get the error. Except that I had a different keyManager but that should not be an issue. to replicate the issue pull the branch and run `node Test/Brambl.js` from the root dir. It should console.log the pk then the body of the request and then the response from bifrost and last the error that it returns. here is the branch https://github.com/Topl/muBrambl/tree/TransferArbitsAndPolysPrototype 
@scasplte2

**Comment by scasplte2** [comment]
> The public key being used (which changes between the Postman run and the
> muBrambl run) is very much important for having Polys and Arbits available
> to move. You can get Polys or Arbits to the account you're using by one of
> two methods

1) Use the default keyfile from the `./keyfiles` directory where the
Bifrost JAR is and load it into muBrambl so that you have Polys and Arbits
to spend. Their should be three keyfiles in that directory but you can use
the local only Balances route to figure out which one has funds available
to it.
2) Create a new key in muBrmabl, note the publicKey, then using Postman
transfer some Polys and Arbits to the key that resides in muBrambl
